name: geomod
channels:
  - conda-forge
  - defaults
  - gimli
dependencies:
  - pygimli==1.3.1
  - pgcore
  - ipython
  - jupyter
  - matplotlib
  - python
  - gempy==2.2.10
  - pooch
  - scooby
  - xarray
  - pip
  - pip:
      - subsurface